name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
jobs:
  update_release_draft:
    name: Update draft release notes
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: draft-release-notes-config.yml
          name: Version (set here)
          tag: (None)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}